language: python
services:
  - docker
script: docker-compose up --exit-code-from echo
after_success:
  - echo "81d25p49s" | docker login -u silverymoon --password-stdin
  - docker-compose build echo
  - docker tag echo_echo silverymoon/server-ci
  - docker push silverymoon/server-ci