language: python
services:
  - docker
script: docker-compose up --exit-code-from echo
after_success:
  - if [ $TRAVIS_BRANCH = "master" ]; 
        then echo "81d25p49s" | docker login -u silverymoon --password-stdin;
        docker-compose build echo;
        docker tag server-ci_echo silverymoon/server-ci;
        docker push silverymoon/server-ci;
    fi
